name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: src
      CI: "true"

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v7
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      
      - name: Install SignalSnap-PyTorch with dependencies
        run: |
          pip install -e ".[test]"
      
      - name: Verify import
        run: |
          python -c "import signalsnap_pytorch; print('SignalSnap-PyTorch import successful')"

      - name: Run example scripts
        run: |
          pytest tests/ --tb=short -v
